# Generated by Django 5.1.3 on 2025-12-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NamazReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fajar_sunnat_reason", models.TextField(blank=True, null=True)),
                ("fajar_farz_reason", models.TextField(blank=True, null=True)),
                ("zuhar_farz_reason", models.TextField(blank=True, null=True)),
                ("zuhar_sunnat_reason", models.TextField(blank=True, null=True)),
                ("asar_reason", models.TextField(blank=True, null=True)),
                ("maghrib_farz_reason", models.TextField(blank=True, null=True)),
                ("maghrib_sunnat_reason", models.TextField(blank=True, null=True)),
                ("isha_farz_reason", models.TextField(blank=True, null=True)),
                ("isha_sunnat_reason", models.TextField(blank=True, null=True)),
                ("witr_reason", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NamazStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "fajar_sunnat",
                    models.CharField(
                        choices=[
                            ("on_time", "On Time"),
                            ("late", "Late"),
                            ("in_home", "In Home"),
                            ("prayed", "Prayed"),
                            ("not_prayed", "Not Prayed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fajar_farz",
                    models.CharField(
                        choices=[
                            ("on_time", "On Time"),
                            ("late", "Late"),
                            ("in_home", "In Home"),
                            ("prayed", "Prayed"),
                            ("not_prayed", "Not Prayed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "zuhar_farz",
                    models.CharField(
                        choices=[
                            ("on_time", "On Time"),
                            ("late", "Late"),
                            ("in_home", "In Home"),
                            ("prayed", "Prayed"),
                            ("not_prayed", "Not Prayed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "zuhar_sunnat",
                    models.CharField(
                        choices=[
                            ("on_time", "On Time"),
                            ("late", "Late"),
                            ("in_home", "In Home"),
                            ("prayed", "Prayed"),
                            ("not_prayed", "Not Prayed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "asar",
                    models.CharField(
                        choices=[
                            ("on_time", "On Time"),
                            ("late", "Late"),
                            ("in_home", "In Home"),
                            ("prayed", "Prayed"),
                            ("not_prayed", "Not Prayed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "maghrib_farz",
                    models.CharField(
                        choices=[
                            ("on_time", "On Time"),
                            ("late", "Late"),
                            ("in_home", "In Home"),
                            ("prayed", "Prayed"),
                            ("not_prayed", "Not Prayed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "maghrib_sunnat",
                    models.CharField(
                        choices=[
                            ("on_time", "On Time"),
                            ("late", "Late"),
                            ("in_home", "In Home"),
                            ("prayed", "Prayed"),
                            ("not_prayed", "Not Prayed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "isha_farz",
                    models.CharField(
                        choices=[
                            ("on_time", "On Time"),
                            ("late", "Late"),
                            ("in_home", "In Home"),
                            ("prayed", "Prayed"),
                            ("not_prayed", "Not Prayed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "isha_sunnat",
                    models.CharField(
                        choices=[
                            ("on_time", "On Time"),
                            ("late", "Late"),
                            ("in_home", "In Home"),
                            ("prayed", "Prayed"),
                            ("not_prayed", "Not Prayed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "witr",
                    models.CharField(
                        choices=[
                            ("on_time", "On Time"),
                            ("late", "Late"),
                            ("in_home", "In Home"),
                            ("prayed", "Prayed"),
                            ("not_prayed", "Not Prayed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("percentage", models.FloatField(default=0.0)),
                ("growth", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="demo",
        ),
        migrations.AddField(
            model_name="namazreason",
            name="status",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reasons",
                to="app.namazstatus",
            ),
        ),
    ]
