# Generated by Django 5.1.3 on 2025-12-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_namazreason_namazstatus_delete_demo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namazstatus",
            name="asar",
            field=models.CharField(
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="fajar_farz",
            field=models.CharField(
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="fajar_sunnat",
            field=models.CharField(
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="isha_farz",
            field=models.CharField(
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="isha_sunnat",
            field=models.CharField(
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="maghrib_farz",
            field=models.CharField(
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="maghrib_sunnat",
            field=models.CharField(
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="witr",
            field=models.CharField(
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="zuhar_farz",
            field=models.CharField(
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="zuhar_sunnat",
            field=models.CharField(
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DailyQuranReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ruku", models.PositiveIntegerField(default=0)),
                ("pages", models.PositiveIntegerField(blank=True, null=True)),
                ("total_rukus", models.PositiveIntegerField(default=0)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("total_time", models.DurationField(blank=True, null=True)),
                ("speed", models.FloatField(default=0.0)),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "growth",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")], default=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
    ]
