# Generated by Django 5.1.3 on 2025-12-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_namazstatus_asar_alter_namazstatus_fajar_farz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyquranreading",
            name="pages",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
