# Generated by Django 5.1.3 on 2025-12-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_dailyquranreading_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namazstatus",
            name="asar",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="fajar_farz",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="fajar_sunnat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="isha_farz",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="isha_sunnat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="maghrib_farz",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="maghrib_sunnat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="witr",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="zuhar_farz",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="namazstatus",
            name="zuhar_sunnat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("in_home", "In Home"),
                    ("prayed", "Prayed"),
                    ("not_prayed", "Not Prayed"),
                    ("not_marked", "Not Marked"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
