# Generated by Django 5.1.3 on 2025-12-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_namazstatus_asar_alter_namazstatus_fajar_farz_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyquranreading",
            unique_together=set(),
        ),
    ]
