# Generated by Django 5.1.3 on 2026-01-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_dailyquranreading_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="sleep_track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("sleep_time", models.TimeField()),
                ("wakeup_time", models.TimeField()),
                ("duration", models.DurationField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
    ]
