# Generated by Django 5.1.3 on 2026-01-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_sleep_track"),
    ]

    operations = [
        migrations.CreateModel(
            name="college_studies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("duration", models.DurationField()),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("machine learning", "Machine Learning"),
                            ("r programming", "R Programming"),
                            ("cloud computing", "Cloud Computing"),
                            ("software testing", "Software Testing"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("note", models.TextField()),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AlterModelOptions(
            name="sleep_track",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="dailyquranreading",
            name="growth",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Up"), (2, "Neutral"), (3, "Down")], default=1
            ),
        ),
    ]
